# Generated by Django 2.1.5 on 2020-07-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retail_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery_agent',
            options={'verbose_name_plural': 'Delivery Agent'},
        ),
    ]
